<a href="https://colab.research.google.com/github/Parikshith21/ML_LAB/blob/master/ANN2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
x=np.array([[2,9],[1,3],[3,6]],dtype=float)
y=np.array([[92],[86],[89]],dtype=float)
deno=np.amax(x,axis=0)
x=x/deno
print("x is:",x)
y=y/100
print("y is:",y)

x is: [[0.66666667 1.        ]
 [0.33333333 0.33333333]
 [1.         0.66666667]]
y is: [[0.92]
 [0.86]
 [0.89]]


In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

#derivative of sig
def derivatives_sigmoid(x):
  return x*(1-x)



In [0]:
iteration=100
learning_rate=0.1
inputlayer_neurons=2
hiddenlayer_neurons=3
output_neurons=1

In [0]:
weight_for_hidden=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bias_for_hidden=np.random.uniform(size=(1,hiddenlayer_neurons))
weight_for_output=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bias_for_output=np.random.uniform(size=(1,output_neurons))

In [0]:
for i in range(iteration):
  hidden=np.dot(x,weight_for_hidden)+bias_for_hidden
  print(hidden)
  hidden_output=sigmoid(hidden)
  output_y=np.dot(hidden_output,weight_for_output)+bias_for_output
  predicted_output=sigmoid(output_y)
  print("y is",predicted_output)
  
  
  #backprop

  #output layer
  Error_for_output=y-predicted_output
  outgrad=derivatives_sigmoid(predicted_output)
  d_output=Error_for_output*outgrad

  #hidden layer
  Error_for_hidden=d_output.dot(weight_for_output.T)
  hiddengrad=derivatives_sigmoid(hidden_output)
  d_hiddenlayer=Error_for_hidden*hiddengrad

[[1.28379023 0.74871107 0.94223981]
 [0.61104917 0.25727456 0.50604553]
 [1.0693962  0.50844232 0.85257883]]
y is [[0.93511076]
 [0.9163191 ]
 [0.92944998]]
[[1.28379023 0.74871107 0.94223981]
 [0.61104917 0.25727456 0.50604553]
 [1.0693962  0.50844232 0.85257883]]
y is [[0.93511076]
 [0.9163191 ]
 [0.92944998]]
[[1.28379023 0.74871107 0.94223981]
 [0.61104917 0.25727456 0.50604553]
 [1.0693962  0.50844232 0.85257883]]
y is [[0.93511076]
 [0.9163191 ]
 [0.92944998]]
[[1.28379023 0.74871107 0.94223981]
 [0.61104917 0.25727456 0.50604553]
 [1.0693962  0.50844232 0.85257883]]
y is [[0.93511076]
 [0.9163191 ]
 [0.92944998]]
[[1.28379023 0.74871107 0.94223981]
 [0.61104917 0.25727456 0.50604553]
 [1.0693962  0.50844232 0.85257883]]
y is [[0.93511076]
 [0.9163191 ]
 [0.92944998]]
[[1.28379023 0.74871107 0.94223981]
 [0.61104917 0.25727456 0.50604553]
 [1.0693962  0.50844232 0.85257883]]
y is [[0.93511076]
 [0.9163191 ]
 [0.92944998]]
[[1.28379023 0.74871107 0.94223981]
 [0.61104917 0.2572745

In [0]:
weight_for_output+=hidden_output.T.dot(d_output)*learning_rate
weight_for_hidden+=x.T.dot(d_hiddenlayer)*learning_rate

In [0]:
print("x is as follows:",x)
print("actual output",y)
print("predicted output",predicted_output)

x is as follows: [[0.66666667 1.        ]
 [0.33333333 0.33333333]
 [1.         0.66666667]]
actual output [[0.92]
 [0.86]
 [0.89]]
predicted output [[0.93511076]
 [0.9163191 ]
 [0.92944998]]
